fix(responsive): text-areas not resizable + improve conversation feed
toctocorg/toctoc pull request #1426
Opened 2024-06-14 07:29 UTC by JNSPK

#1382

<img src="https://media.giphy.com/media/xpI7aoCzJHmPp95Lcq/giphy.gif?cid=790b7611o2wezwdljczyq30guv53em125ij8wfim3fjxtewl&ep=v1_gifs_search&rid=giphy.gif&ct=g">

2024-06-15 13:29 UTC, douglasduteil requested changes

2024-06-15 13:29 UTC, douglasduteil commented on apps/www/app/(main)/door/[code]/(private)/exchanges/inbox/[exchange_id]/[thread_id]/_client/Conversation_Form.tsx
> +                className: "peer h-[8rem] w-full resize-none rounded-2xl pr-10",
```suggestion
                className: "peer h-32 w-full resize-none rounded-2xl pr-10",
```

2024-06-15 13:29 UTC, douglasduteil commented on apps/www/app/(main)/door/[code]/(private)/exchanges/inbox/[exchange_id]/[thread_id]/page.tsx
> +      <div className="max-h-[calc(100%-16rem)] overflow-y-auto py-4 pr-5 md:max-h-full">
```suggestion
      <div className="max-h-[calc(100%_-_theme(spacing.64))] overflow-y-auto py-4 pr-5 md:max-h-full">
```

2024-06-15 13:29 UTC, douglasduteil commented on apps/www/app/(main)/door/[code]/(private)/inbox/[thread_id]/_client/Conversation_Form.tsx
> +                className: "peer h-[8rem] w-full resize-none rounded-2xl pr-10",
```suggestion
                className: "peer h-32 w-full resize-none rounded-2xl pr-10",
```

2024-06-15 13:29 UTC, douglasduteil commented on apps/www/app/(main)/door/[code]/(private)/inbox/[thread_id]/page.tsx
> +      <div className="max-h-[calc(100%-3rem)] overflow-y-auto py-4 pr-5">
```suggestion
      <div className="max-h-[calc(100%_-_theme(spacing.12))] overflow-y-auto py-4 pr-5">
```

2024-06-19 10:41 UTC, toctocorg approved these changes
> Il y a toujours un problème avec ton prettier 👀 ...

2024-06-19 10:53 UTC, douglasduteil approved these changes

2024-06-19 10:53 UTC, douglasduteil commented on apps/www/app/(main)/door/[code]/(private)/exchanges/inbox/[exchange_id]/[thread_id]/page.tsx
> +   top-16 grid
```suggestion
   top-16
   grid 
```

2024-06-19 10:54 UTC, merged